// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoSearchProbe() {
  return window['go']['main']['App']['AutoSearchProbe']();
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function ClearLogFile(arg1) {
  return window['go']['main']['App']['ClearLogFile'](arg1);
}

export function ClosePort(arg1) {
  return window['go']['main']['App']['ClosePort'](arg1);
}

export function ExportLogs(arg1, arg2) {
  return window['go']['main']['App']['ExportLogs'](arg1, arg2);
}

export function GetDeviceName(arg1, arg2) {
  return window['go']['main']['App']['GetDeviceName'](arg1, arg2);
}

export function GetPortStatus(arg1, arg2) {
  return window['go']['main']['App']['GetPortStatus'](arg1, arg2);
}

export function GetStoredPassword(arg1) {
  return window['go']['main']['App']['GetStoredPassword'](arg1);
}

export function GetUSBTree() {
  return window['go']['main']['App']['GetUSBTree']();
}

export function OpenPort(arg1) {
  return window['go']['main']['App']['OpenPort'](arg1);
}

export function OpenSystemTerminal() {
  return window['go']['main']['App']['OpenSystemTerminal']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadLogs(arg1) {
  return window['go']['main']['App']['ReadLogs'](arg1);
}

export function ResetHub(arg1, arg2) {
  return window['go']['main']['App']['ResetHub'](arg1, arg2);
}

export function RestoreDefault(arg1, arg2) {
  return window['go']['main']['App']['RestoreDefault'](arg1, arg2);
}

export function SavePortStates(arg1, arg2) {
  return window['go']['main']['App']['SavePortStates'](arg1, arg2);
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function SetDeviceName(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetDeviceName'](arg1, arg2, arg3);
}

export function SetPortStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetPortStatus'](arg1, arg2, arg3, arg4);
}

export function SetStoredPassword(arg1, arg2) {
  return window['go']['main']['App']['SetStoredPassword'](arg1, arg2);
}

export function SetVBUSPower(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetVBUSPower'](arg1, arg2, arg3);
}

export function WriteLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteLog'](arg1, arg2, arg3);
}
