// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hubmanager} from '../models';

export function AutoSearchProbe():Promise<Array<hubmanager.DeviceInfo>>;

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ClearLogFile(arg1:string):Promise<void>;

export function ClosePort(arg1:string):Promise<void>;

export function ExportLogs(arg1:string,arg2:string):Promise<void>;

export function GetDeviceName(arg1:string,arg2:string):Promise<string>;

export function GetPortStatus(arg1:string,arg2:number):Promise<Record<number, boolean>>;

export function GetStoredPassword(arg1:string):Promise<string>;

export function GetUSBTree():Promise<string>;

export function OpenPort(arg1:string):Promise<void>;

export function OpenSystemTerminal():Promise<void>;

export function QuitApp():Promise<void>;

export function ReadLogs(arg1:string):Promise<Array<string>>;

export function ResetHub(arg1:string,arg2:string):Promise<string>;

export function RestoreDefault(arg1:string,arg2:string):Promise<string>;

export function SavePortStates(arg1:string,arg2:string):Promise<string>;

export function SendCommand(arg1:string,arg2:string):Promise<string>;

export function SetDeviceName(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetPortStatus(arg1:string,arg2:string,arg3:Record<number, boolean>,arg4:number):Promise<string>;

export function SetStoredPassword(arg1:string,arg2:string):Promise<void>;

export function SetVBUSPower(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function WriteLog(arg1:string,arg2:string,arg3:string):Promise<void>;
