// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {hubmanager} from '../models';

export function AddScheduledTask(arg1:config.ScheduledTask):Promise<void>;

export function AutoSearchProbe():Promise<Array<hubmanager.DeviceInfo>>;

export function ClearLogFile(arg1:string):Promise<void>;

export function CloseCurrentPort():Promise<void>;

export function GetScheduledTasks():Promise<Array<config.ScheduledTask>>;

export function GetStoredPassword(arg1:string):Promise<string>;

export function GetUSBTree():Promise<string>;

export function OpenPort(arg1:string):Promise<void>;

export function QuitApp():Promise<void>;

export function ReadLogs(arg1:string):Promise<Array<string>>;

export function RemoveScheduledTask(arg1:string):Promise<void>;

export function SendCommand(arg1:string):Promise<string>;

export function SetStoredPassword(arg1:string,arg2:string):Promise<void>;

export function UpdateScheduledTask(arg1:config.ScheduledTask):Promise<void>;

export function WriteLog(arg1:string,arg2:string,arg3:string):Promise<void>;
