// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScheduledTask(arg1) {
  return window['go']['main']['App']['AddScheduledTask'](arg1);
}

export function AutoSearchProbe() {
  return window['go']['main']['App']['AutoSearchProbe']();
}

export function ClearLogFile(arg1) {
  return window['go']['main']['App']['ClearLogFile'](arg1);
}

export function CloseCurrentPort() {
  return window['go']['main']['App']['CloseCurrentPort']();
}

export function ClosePort(arg1) {
  return window['go']['main']['App']['ClosePort'](arg1);
}

export function GetScheduledTasks() {
  return window['go']['main']['App']['GetScheduledTasks']();
}

export function GetStoredPassword(arg1) {
  return window['go']['main']['App']['GetStoredPassword'](arg1);
}

export function GetUSBTree() {
  return window['go']['main']['App']['GetUSBTree']();
}

export function OpenPort(arg1) {
  return window['go']['main']['App']['OpenPort'](arg1);
}

export function OpenSystemTerminal() {
  return window['go']['main']['App']['OpenSystemTerminal']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadLogs(arg1) {
  return window['go']['main']['App']['ReadLogs'](arg1);
}

export function RemoveScheduledTask(arg1) {
  return window['go']['main']['App']['RemoveScheduledTask'](arg1);
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2);
}

export function SetStoredPassword(arg1, arg2) {
  return window['go']['main']['App']['SetStoredPassword'](arg1, arg2);
}

export function UpdateScheduledTask(arg1) {
  return window['go']['main']['App']['UpdateScheduledTask'](arg1);
}

export function WriteLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteLog'](arg1, arg2, arg3);
}
